<?php

if ( ! defined( 'ABSPATH' ) ) {
	die( '-1' );
}

return array(
	'name'                    => __( 'ILC Recent News', 'ilc' ),
	'base'                    => 'ilc_recent_news',
	'icon'                    => 'vcex-icon-box vcex-icon ticon ticon-newspaper-o',
	'is_container'            => false,
	'show_settings_on_create' => false,
	'category'                => __( 'ILC', 'ilc' ),
	'description'             => __( 'Dispaly recent news.', 'ilc' ),
	'php_class_name'          => 'ILC_VC_Recent_News',
	'params'                  => array(
		array(
			'type'        => 'textfield',
			'heading'     => __( 'Widget title', 'js_composer' ),
			'param_name'  => 'title',
			'admin_label' => true,
			'description' => __( 'Enter text used as widget title (Note: located above content element).', 'js_composer' ),
		),
		array(
			'type'               => 'autocomplete',
			'heading'            => __( 'Include Categories', 'ilc' ),
			'param_name'         => 'include_categories',
			'param_holder_class' => 'vc_not-for-custom',
			'admin_label'        => true,
			'settings'           => array(
				'multiple'       => true,
				'min_length'     => 1,
				'groups'         => false,
				'unique_values'  => true,
				'display_inline' => true,
				'delay'          => 0,
				'auto_focus'     => true,
			),
			'group'              => __( 'Query', 'ilc' ),
		),
		array(
			'type'               => 'autocomplete',
			'heading'            => __( 'Exclude Categories', 'ilc' ),
			'param_name'         => 'exclude_categories',
			'param_holder_class' => 'vc_not-for-custom',
			'admin_label'        => true,
			'settings'           => array(
				'multiple'       => true,
				'min_length'     => 1,
				'groups'         => false,
				'unique_values'  => true,
				'display_inline' => true,
				'delay'          => 0,
				'auto_focus'     => true,
			),
			'group'              => __( 'Query', 'ilc' ),
		),
		array(
			'type'        => 'textfield',
			'heading'     => __( 'Number of news', 'ilc' ),
			'param_name'  => 'limit',
			'value'       => '6',
			'description' => __( 'Enter the limit of news to show. Leave empty to show all.', 'ilc' ),
			'group'       => __( 'Query', 'total-child' ),
		),
		array(
			'type'       => 'dropdown',
			'heading'    => __( 'Display Type', 'total-child' ),
			'param_name' => 'display_type',
			'value'      => array(
				__( 'List', 'ilc' ) => 'list',
				__( 'Grid', 'ilc' ) => 'grid',
			),
			'std' => 'list',
			'group'      => __( 'View', 'ilc' ),
		),
		array(
			'type'       => 'dropdown',
			'heading'    => __( 'Grid Size', 'total-child' ),
			'param_name' => 'grid_size',
			'value'      => array(
				__( '1', 'ilc' ) => '1',
				__( '2', 'ilc' ) => '2',
				__( '3', 'ilc' ) => '3',
				__( '4', 'ilc' ) => '4',
			),
			'std' => '3',
			'dependency' => array(
				'element' => 'display_type',
				'value'   => array( 'grid' ),
			),
			'group'      => __( 'View', 'ilc' ),
		),
		array(
			'type'       => 'vcex_ofswitch',
			'std'        => 'true',
			'heading'    => __( 'Show Excerpt', 'ilc' ),
			'param_name' => 'show_excerpt',
			'group'       => __( 'View', 'ilc' ),
		),
		array(
			'type'        => 'textfield',
			'heading'     => __( 'Excerpt Length', 'ilc' ),
			'param_name'  => 'excerpt_length',
			'value'       => '28',
			'description' => __( 'Enter excerpt words limit.', 'ilc' ),
			'group'       => __( 'View', 'ilc' ),
			'dependency' => array(
				'element' => 'show_excerpt',
				'value'   => array( 'true' ),
			),
		),
		array(
			'type'       => 'vcex_ofswitch',
			'std'        => 'false',
			'heading'    => __( 'Show Pagination', 'ilc' ),
			'param_name' => 'show_pagination',
			'group'       => __( 'View', 'ilc' ),
		),
		array(
			'type'       => 'vcex_ofswitch',
			'std'        => 'true',
			'heading'    => __( 'Show View All Link', 'ilc' ),
			'param_name' => 'show_view_all',
			'group'       => __( 'View', 'ilc' ),
		),
		array(
			'type'        => 'textfield',
			'heading'     => __( 'View All links Text', 'ilc' ),
			'param_name'  => 'view_all_text',
			'description' => __( 'Enter text used as view all events link.', 'ilc' ),
			'group'       => __( 'View', 'ilc' ),
			'dependency' => array(
				'element' => 'show_view_all',
				'value'   => array( 'true' ),
			),
		),
		array(
			'type'        => 'textfield',
			'heading'     => __( 'View All links URL', 'js_coilcmposer' ),
			'param_name'  => 'view_all_url',
			'description' => __( 'Enter URL used as view all events link.', 'ilc' ),
			'group'       => __( 'View', 'ilc' ),
			'dependency' => array(
				'element' => 'show_view_all',
				'value'   => array( 'true' ),
			),
		),
		vc_map_add_css_animation(),
		array(
			'type'        => 'el_id',
			'heading'     => __( 'Element ID', 'js_composer' ),
			'param_name'  => 'el_id',
			'description' => sprintf( __( 'Enter element ID (Note: make sure it is unique and valid according to <a href="%s" target="_blank">w3c specification</a>).', 'js_composer' ), 'http://www.w3schools.com/tags/att_global_id.asp' ),
		),
		array(
			'type'        => 'textfield',
			'heading'     => __( 'Extra class name', 'js_composer' ),
			'param_name'  => 'el_class',
			'description' => __( 'Style particular content element differently - add a class name and refer to it in custom CSS.', 'js_composer' ),
		),
		array(
			'type'       => 'css_editor',
			'heading'    => __( 'CSS box', 'js_composer' ),
			'param_name' => 'css',
			'group'      => __( 'Design Options', 'js_composer' ),
		),
	),
);
